### ISSUE TITLE
Error in arcasHLA partial module

### ISSUE THREAD

**Issue by VitorAguiar** [RabadanLab/arcasHLA#1]
Hello,

in my attempt to run 'arcasHLA partial', I got an error because there was no 'database/parameters.p' file as required in line #346 of 'scripts/partial.py'. I tried replacing this with 'dat/info/parameters.p', then the program runs for while until it crashes again with the following message:

`File "./scripts/partial.py", line 528, in <module>`
`    args.keep_files)`
`ValueError: not enough values to unpack (expected 3, got 2)`

I would appreciate if you could look into this.
Thank you

**Comment by roseorenbuch** [comment]
Hi Vitor,
The partial module is fixed now.
