### ISSUE TITLE
Deprecation of kallisto pseudo

### ISSUE THREAD

**Issue by huzuner** [RabadanLab/arcasHLA#109]
Dear developers,

Since the version update of kallisto ==0.46.2, the usage of `kallisto pseudo` is deprecated and in the latest version` v0.50.0`, it is now completely removed. Hence,`arcashla genotype` cannot be executed any longer with conda installation since it currently downloads the latest version of kallisto due to having ` kallisto >=0.44.0` as a dependency.

**Comment by deve105** [comment]
I would like to know if there is any solution for this problem? Thank you

**Comment by huzuner** [comment]
> I would like to know if there is any solution for this problem? Thank you

For now you can install arcashLA via conda and use it without a problem, since the version of kallisto in Bioconda recipe was fixed to a previous version.

**Comment by abuendia** [comment]
Thanks. conda env with bioconda install of `kallisto` added in #120.
