### ISSUE TITLE
Kallisto with single-end data?

### ISSUE THREAD

**Issue by acrinklaw** [RabadanLab/arcasHLA#13]
I have a rather large set of single-end data that I'd like to perform HLA typing for and would love to use this tool but I am hung up on one thing. arcasHLA uses Kallisto and for single-end this requires fragment length and std deviation of fragment length. Quickly looking through I see that this is estimated as read length and std deviation of read length in this case. Will this affect results down stream? From what I have found it seems that Kallisto can be rather picky when it comes to these parameters. This is most likely not an issue for a vast majority as it seems paired-end is more common :^(

**Comment by acrinklaw** [comment]
From what I understand read length != fragment length 
![img](http://www.frontiersin.org/files/Articles/77572/fgene-05-00005-HTML/image_m/fgene-05-00005-g001.jpg)
but I have not found any published data on how varying these parameters by +/- X bp affects the alignments. Was just wondering if this had been looked into or if it even had an effect at all.

**Comment by IoanFilip2** [comment]
Dear Austin, thanks for your interest in our tool. I'm sorry for the delay in replying. Indeed, we perform an estimation of mean and std of read length and not fragment length, but we have found that this estimate still works well with Kallisto from single-end protocols. You may also experiment by running arcasHLA with different predicted fragment lengths to check the robustness of the inferred genotype. Thanks!
