### ISSUE TITLE
DPA1 typing

### ISSUE THREAD

**Issue by matzefant** [RabadanLab/arcasHLA#15]
Hello,
would it be possible for your tool to type also the DPA1 allele?

Kind regards,
Matthias

**Comment by IoanFilip2** [comment]
Dear Matthias, yes you should be able to type DPA1 with arcasHLA as long as you specify this requirement with the -g A,B,C,DPA1,... flag for arcasHLA genotype as the DPA1 alleles are present in IMGT/HLA database. Thanks.

**Comment by matzefant** [comment]
Hello, thank you for the response, I installed the tool and it was working nicely on some RNAseq samples :) 
Could I ask one more question: I also tried a whole-genome sequencing sample of the same individual as input and it basically gave me a similar result (except for one different typing in DQB1). Do you have experiences with HLA typing from WGS using arcasHLA and is it fine to use it for that purpose?

Kind regards,
Matthias

**Comment by IoanFilip2** [comment]
Hi Matthias, we have not tested arcasHLA on WGS; arcasHLA was designed for RNAseq. It may work, but particular attention has to be placed on creating the reference index and the source files that are used. For WGS, I would recommend trying HISAT2 (https://ccb.jhu.edu/software/hisat2/index.shtml). Their approach is similar to ours, but their tool was made for WGS.
