### ISSUE TITLE
Allele specific expression

### ISSUE THREAD

**Issue by ahy1221** [RabadanLab/arcasHLA#16]
Dear developers:
Thanks for the excellent tools.
After getting genotype from arcasHLA , I was wondering that is that possible to get allele specific expression using these genotypes ?
The actual question to me is that I was trying to quantify HLA allele expression from single cell Smartseq2 RNA data. 
So far, I got the HLA genotype from bulk RNA seq. 
Then is that any possible way to apply these HLA genotype to quantify specific HLA allele expression for scRNA data (assuming these single cell data are from the same sample) ?

Thank you

**Comment by IoanFilip2** [comment]
Dear Yao, Thank you for your interest in our tool. We are currently developing a new method based on arcasHLA to perform precisely allele-specific quantification, precisely what you are asking for. We can update you soon, once we are able to release it in beta version. One challenge that will come up in scRNAseq is the dropout effect, which could give incorrect estimates of HLA allele ratios. We will be happy to discuss further. Thanks for raising the topic.

**Comment by ahy1221** [comment]
Thank you very much! Looking forward to your update
One simple but naive idea comes up to my mind  is that maybe I can extract sequence by HLA genotype acquired from arcasHLA, and then use kallisto to get TPM and estimated counts for these different alleles ? 
Do you think that is a manually solution to do that before your software release ?

**Comment by IoanFilip2** [comment]
Your suggested approach is reasonable, and it is similar to the starting point of our solution. As mentioned before, I am not sure how reliable such results can be from single-cell data because the key challenges with this platform can affect HLA typing and quantification particularly due to the polymorphic nature of that locus. We are also experimenting with our own tool applies to scRNAseq data, and will release updates when we reach a more definite conclusion. Thanks for your inquiry!

**Comment by ahy1221** [comment]
Thanks for your replying . 
So far at least for my own data generated by Smartseq2, I found the results from arcasHLA is reliable if we use corresponding bulk RNA data as positive control. arcasHLA generated the same HLA genotypes for scRNA data as bulk data.

**Comment by IoanFilip2** [comment]
That is good to hear, and very interesting actually. We will be evaluating more thoroughly and benchmarking arcasHLA performance with single cell data.

**Comment by jfx319** [comment]
See also:
- https://github.com/10XGenomics/scHLAcount
- https://www.biorxiv.org/content/10.1101/750612v1
which recommends running arcasHLA first for some performance benefits

**Comment by yhfteng** [comment]
Hi, 
It's great to know that some of you have tried arcasHLA on scRNA seq data  for HLA genotyping purpose. scHLAcount mentioned that arcasHLA performs better at genotyping so I was looking to use arcasHLA. I have some 10X scRNAseq data and have tried using the possorted_genome.bam files as inputs to arcasHLA but without success - there are no extracted reads. I have tried arcasHLA successfully with other bulk RNAseq data but not for the 10x scRNA. Could anybody point out what I could have done/not done that could have gone wrong? Thanks very much!

**Comment by IoanFilip2** [comment]
Can you please specify the exact command used and the input files? To use arcasHLA for genotyping from scRNA-seq, you need to treat the expression data as bulk (ignoring barcode read information) and only use the sequencing read data. Whether it should be run as single-end or pair-end depends on the chemistry used. Please provide all necessary details in order to assess the correct way of running the tool on 10X output.

**Comment by jfx319** [comment]
@yhfteng I can confirm that arcasHLA works on 10x 5' GEX data

Be aware of the 5' vs 3' coverage difference for HLA on https://github.com/10XGenomics/scHLAcount

If you're following those 10x recommended sequencing length configurations, then your GEX data might not truly be PE (read1 does not have gene information) -- if so, make sure to discard the extracted read1.fq if it doesn't contain gene information.

**Comment by yhfteng** [comment]
Thank you  @IoanFilip2  and @jfx319 for your prompt replies. Yes, you are right the 10X data is not truly PE ( I saw that after I converted the 10x output file - possorted_genome.bam file into fastq to take a look) and saw that read1 does have gene information. I reran the command:
arcasHLA extract [options] /path/to/sample.bam  
without the --paired option and it worked.
Thanks all!
