### ISSUE TITLE
Homozygous versus heterozygous with one allele missing

### ISSUE THREAD

**Issue by slowkow** [RabadanLab/arcasHLA#20]
Thanks for the great tool! I ran it on a bunch of RNA-seq samples and so far it seems to be working.

Suppose I receive the following result from arcasHLA:

```
{
  "A": ["A*02:816", "A*03:01:77"],
  "B": ["B*83:01"],
  "DQB1": ["DQB1*03:03:02", "DQB1*03:94"]
}
```

I'd like to ask if you might be able to help me understand the answers to a few questions:

## Question 1

Is it true that `A*02:816` is on the same haplotype as `DQB1*03:03:02`? In other words, are the alleles of different genes in phase with each other?

Does arcasHLA claim that we have these two chromosomes?

```
chromosome A:    A*02:816    DQB1*03:03:02

chromosome B:    A*03:01:77  DQB1*03:94
```

Alternatively, are the genotypes unphased, so arcasHLA does not distinguish the above situation from the following situation?

```
chromosome A:    A*02:816    DQB1*03:94

chromosome B:    A*03:01:77  DQB1*03:03:02
```

## Question 2

What is the genotype for HLA-B? Is it homozygous with two copies of `B*83:01`? Or, is it actually heterozygous with one copy of `B*83:01` and one copy of unknown genotype?

Is arcasHLA claiming that this is the situation?

```
chromosome A:    B*83:01

chromosome B:    B*83:01
```

Or this?

```
chromosome A:    B*83:01

chromosome B:    Unknown
```

## Question 3

Does arcasHLA offer any way to assess the probability or the confidence for the genotype calls?

I can see this output in the `genes.json` file:
```
"A": [7378.0, 1202, 0.10358776417015307]
```

Which corresponds to this output in the `genotype.log` file:

```
[alignment] Observed HLA genes:
                gene          abundance    read count    classes
                HLA-A            10.36%          7378       1202
                HLA-B             6.80%          4807        989
                HLA-C            10.30%          7354       1090
```

I will try to use these numbers to assess the confidence, but I wonder if you are able to get some calibrated p-value or probability from the kallisto results?

## Question 4

Do you have any sense of what the read pileup coverage in a genome browser should look like in order to get accurate genotype calls?

Thank you!

**Comment by IoanFilip2** [comment]
Thanks for your inquiry.
Q1. The genotype results are unphased, and alleles are returned independently for each gene. 
Q2. If a single allele is returned, arcasHLA claims that for the gene in question the individual is homozygous for the specific allele (in your example for B*83:01 for HLA-B).
Q3. At this time, there is no confidence or p-value result with the returned genotype call. In a future release, we hope to include such information.
Q4. The read pileup should show coverage of the full gene, where possible (e.g. if total RNA-seq protocol is used). At the very least, there should be good coverage of exons 2 and 3 that contain the highest variation and determine HLA typing to a large extent. 
Hope this answers your questions.
Best,
Ioan

**Comment by slowkow** [comment]
Thank you for the very prompt response!

In general, it seems that 5p libraries have better coverage of exons 2 and 3 than 3p libraries.

You might consider reporting the information about exon coverage in the results. Also, this information might be used to compute a confidence in the genotype calls.

Here is an example of good coverage from a 5p library:

![image](https://user-images.githubusercontent.com/209714/72309996-8e3e0680-364e-11ea-9a16-4824b6045309.png)


And here is an example of poor coverage from a 3p library:

![image](https://user-images.githubusercontent.com/209714/72309984-87af8f00-364e-11ea-912d-0b0482077315.png)
