### ISSUE TITLE
Reads from alt chromosomes don't seem to be extracted

### ISSUE THREAD

**Issue by dsobral** [RabadanLab/arcasHLA#21]
I've aligned my samples against the hg38 human reference provided by GATK, which includes alt chromosomes such as the HLA loci. Nonetheless, when I run arcasHLA, it only extracts data from chromosome 6, although I saw in the code that it should also extract from those alt chromosomes... for some reason it doesn't seem to be finding them?

**Comment by IoanFilip2** [comment]
Thanks for your inquiry. Please make sure the reference file has the ALTs in header properly formatted and that the attached file from arcasHLA (arcasHLA/dat/info/decoys_alts.p) contains the ALTs from GATK.
