### ISSUE TITLE
Obtaining RPKM like counts

### ISSUE THREAD

**Issue by ramit29** [RabadanLab/arcasHLA#22]
Hi I am interested in obtaining RPKM like data from arcasHLA output. I noticed that one of the output fines(*samplename.genes.json) has the following output format : HLA-type: [read count, equivalence class, ]

I was wondering if an estimate of expression for a specific allele type can be obtained by:
RPKM = (Read count x equivalence class)/1,000,000

ex: HLA-A:[20000,10000,]
Can HLA-A RPKM = (20000x10000)/1000000 = 200 ?

**Comment by IoanFilip2** [comment]
Thank you for using our tool. Can you please clarify what you are trying to accomplish with your definition?
