### ISSUE TITLE
Broken: arcasHLA reference --version 3.24.0

### ISSUE THREAD

**Issue by jwhite007** [RabadanLab/arcasHLA#23]
```
$ ./arcasHLA reference --version 3.24.0
[reference] Error: dat/IMGTHLA/hla.dat empty or corrupted.
```

It appears that the hash for version 3.24.0 in parameters.p is incorrect. Searching the IMGTHLA repo, I cannot find a commit with hash of c5acf7a4342869351b2382b1cc1d1b5763e7e04e: https://github.com/ANHIG/IMGTHLA/search?q=hash%3Ahash%3Ac5acf7a4342869351b2382b1cc1d1b5763e7e04e&type=Commits.

I did find what appears to be a valid commit for 3.24.0 and attempted to use the hash for it, 4a0401af6be02ca688adeef3f63f5e55288d14fe; however, that fails with the same error message.

**Comment by IoanFilip2** [comment]
Thank you for using our tool. We have not been able to replicate this error. Are you able to successfully fetch any other IMGT/HLA database version? Did you properly install arcasHLA?

**Comment by jwhite007** [comment]
@IoanFilip2 

Thank you for your response.

This is not an issue, purely my fault. I had neglected to initialize git-lfs for the user which I was running arcasHLA under.
