### ISSUE TITLE
docker recipe

### ISSUE THREAD

**Issue by jfx319** [RabadanLab/arcasHLA#24]
The steps to install are quite involved -- may I request a Dockerfile recipe to be hosted on this official repository? 

There are a few existing ones already, with some already built and hosted on dockerhub:
- https://github.com/tengfei/docker-arcasHLA/blob/master/Dockerfile
- https://github.com/adeschen/docker-arcasHLA/blob/master/Dockerfile
- https://github.com/zlskidmore/docker-arcasHLA/blob/master/Dockerfile

But these will eventually lag behind. Some edited version inspired by these could be officially hosted here and verified for the most recent release of arcasHLA; it would be much easier for users to test the tool on their own data and be confident that the latest arcasHLA is being used. You can trigger an autobuild on dockerhub pointing to new updates to this recipe.

Ideally, for academic settings with HPC environments, the container should also run fine after conversion from docker to singularity, but this is more minor. Happy to volunteer to test.

**Comment by IoanFilip2** [comment]
Thank you for this comment and important proposal. Our plan is to eventually release and host a vetted Docker image for arcasHLA genotyping functionality and include on-going developments. In the meantime, here is our recommended Dockerfile for arcasHLA:

```
# work from latest LTS ubuntu release
FROM ubuntu:18.04

# set the environment variables
ENV kallisto_version 0.44.0
ENV samtools_version 1.9
ENV bedtools_version 2.29.2
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# run update and install necessary tools from package manager
RUN apt-get update -y && apt-get install -y \
    build-essential \
    cmake \
    zlib1g-dev \
    libhdf5-dev \
    libnss-sss \
    curl \
    autoconf \
    bzip2 \
    python3-dev \
    python3-pip \
    python3-biopython \
    pigz \
    git \
    libncurses5-dev \
    libncursesw5-dev \
    libbz2-dev \
    liblzma-dev \
    bzip2 \
    unzip

# install python libraries
RUN pip3 install numpy
RUN pip3 install scipy
RUN pip3 install pandas

# install kallisto
RUN mkdir -p /usr/bin/kallisto \
    && curl -SL https://github.com/pachterlab/kallisto/archive/v${kallisto_version}.tar.gz \
    | tar -zxvC /usr/bin/kallisto

RUN mkdir -p /usr/bin/kallisto/kallisto-${kallisto_version}/build
RUN cd /usr/bin/kallisto/kallisto-${kallisto_version}/build && cmake ..
RUN cd /usr/bin/kallisto/kallisto-${kallisto_version}/ext/htslib && autoreconf
RUN cd /usr/bin/kallisto/kallisto-${kallisto_version}/build && make
RUN cd /usr/bin/kallisto/kallisto-${kallisto_version}/build && make install

# install samtools
WORKDIR /usr/bin/
RUN curl -SL https://github.com/samtools/samtools/releases/download/${samtools_version}/samtools-${samtools_version}.tar.bz2 \
    > samtools-${samtools_version}.tar.bz2
RUN tar -xjvf samtools-${samtools_version}.tar.bz2
WORKDIR /usr/bin/samtools-${samtools_version}
RUN ./configure
RUN make
RUN make install

# install bedtools
WORKDIR /usr/bin
RUN curl -SL https://github.com/arq5x/bedtools2/releases/download/v${bedtools_version}/bedtools-${bedtools_version}.tar.gz \
    > bedtools-${bedtools_version}.tar.gz
RUN tar -xzvf bedtools-${bedtools_version}.tar.gz
WORKDIR /usr/bin/bedtools2
RUN make
RUN ln -s /usr/bin/bedtools2/bin/bedtools /usr/bin/bedtools

# git lfs
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install -y git-lfs
RUN git lfs install --system --skip-repo

# install arcasHLA
WORKDIR /home/
RUN git clone https://github.com/RabadanLab/arcasHLA.git arcasHLA-master

ENV PATH="${PATH}:/home/arcasHLA-master/"

RUN arcasHLA reference --update
```

**Comment by jfx319** [comment]
Thanks!

I can confirm that this recipe builds successfully and converts successfully to a singularity image on a CentOS HPC:

```bash
hostnamectl
#  Operating System: CentOS Linux 7 (Core)
#            Kernel: Linux 3.10.0-957.27.2.el7.x86_64
```

The latest IMGT is also downloaded at build time and is ready to use. 

All the functions run fine on the included `/home/arcasHLA-master/test/test.bam`. 

final `test.genotype.json`
```
{"A": ["A*01:01:01", "A*03:01:01"], 
 "B": ["B*39:39:01", "B*07:02:01"], 
 "C": ["C*01:02:01", "C*08:01:01"], 
 "DPB1": ["DPB1*14:01:01", "DPB1*02:01:02"], 
 "DQA1": ["DQA1*05:03:01", "DQA1*02:01:01"], 
 "DQB1": ["DQB1*06:04:01", "DQB1*02:02:01"], 
 "DRB1": ["DRB1*03:02:01", "DRB1*10:01:01"]}
```
It's slightly different due to the newer IMGT version versus the older one used in the README example.
