### ISSUE TITLE
Merge jsons error

### ISSUE THREAD

**Issue by amalthomas111** [RabadanLab/arcasHLA#27]
```
./arcasHLA/arcasHLA merge -i genotypeoutputs/ -o mergedoutput --run test
```
Traceback (most recent call last):
  File "/myhome/arcasHLA/scripts/merge.py", line 173, in <module>
    'genes')
  File "/myhome/arcasHLA/scripts/merge.py", line 92, in process_count
    lines = lines.split('-'*80)[2].split('\n')
IndexError: list index out of range

**Comment by marzamKI** [comment]
Hey,
I also had this error, but was able to get the merged file after creating a new directory containing only the .genotype.json files.
M

**Comment by kwanghoon821** [comment]
me too, but like marzamKI said I got merged file too.

**Comment by tpereachamblee** [comment]
Thanks for using the tool.The latest update removes a bug that came up before when merging the genes.json outputs.
