### ISSUE TITLE
Can't install/update references

### ISSUE THREAD

**Issue by jfnavarro** [RabadanLab/arcasHLA#28]
Hi, 

I do not seem to be able to install and run arcasHLA. 

I cloned the repository and when I try:

`./arcasHLA reference --update` 

I get the following error:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/jose.fernandez.navarro/shared/arcasHLA/scripts/../dat/IMGTHLA/wmda/hla_nom_p.txt'`

If I git clone `IMGTHLA` to `dat` and I try again then I get this error:

`[reference] Error: dat/IMGTHLA/hla.dat empty or corrupted.`

I get the same error if I try specific versions like 3.24.0 and so on...

**Comment by IoanFilip2** [comment]
Thanks for using the tool. We have not been able to replicate this error. Do you have all the dependencies in order, as instructed? It seems there is something wrong with your folder structure.

**Comment by jfnavarro** [comment]
I solved the issue by installing git-lfs for all repositories instead of just arcasHLA. 

Anyways, now I get another error:

usage: arcasHLA partial [options] -G genotype.json FASTQ
arcasHLA partial: error: The format of sample_header.genotype.json is invalid.

The JSON file is correct.

**Comment by WombedTadpole1** [comment]
Hi! Could you explain more, please, what did you mean by installing 'git lfs for all repositories instead of just arcasHLA'?
