### ISSUE TITLE
single cell RNA sequencing

### ISSUE THREAD

**Issue by MySelvan** [RabadanLab/arcasHLA#29]
I have been using arcasHLA for bulk RNA and it has been great. Can arcasHLA be applied to single cell RNA sequencing data too

**Comment by IoanFilip2** [comment]
Thank you for using our tool. Please see a few previous threads already regarding single-cell seq. What are you trying to accomplish with arcasHLA on single-cell RNAseq?

**Comment by MySelvan** [comment]
I have fastq files (in the form of I1, R1 and R2) from ScRNA-seq and would like to identify the HLA-genotype. Would it be appropriate to run arcasHLA using  the fastq file (only R2 with the sequence)? Are any pre-processing required before running arcasHLA or should I be aware of any caveats of the HLA genotypes identified from ScRNA-Seq? 
I checked the previous threads and it was mentioned arcasHLA performance will be tested and benchmarked with scRNA-seq data. Could you please let me know how was the performance from such analysis?

**Comment by tpereachamblee** [comment]
Thank you for using our tool. Please see the explanation provided in issue #49
