### ISSUE TITLE
merge.py

### ISSUE THREAD

**Issue by kwanghoon821** [RabadanLab/arcasHLA#31]
I download new merge.py file, and ran arcasHLA. 

Errors that are exist before are solved I think, but new Syntax error appeared.

  **File "/home/sunghyepark_lab/packages/arcasHLA/scripts/merge.py", line 7
     < !DOCTYPE html >    <- (I add spaces at both side to write this issue)
     ^
SyntaxError: invalid syntax**

Merged file were made like before.

**Comment by tpereachamblee** [comment]
Thank you for using our tool. We cannot replicate the issue you are posting here. Please check if the dependencies are properly installed, and post the exact command as well as the output in that case.

**Comment by tpereachamblee** [comment]
This is not an issue related to our tool. Please refrain from posting undocumented user errors here.
