### ISSUE TITLE
Why is there no install script. This is python.

### ISSUE THREAD

**Issue by xguse** [RabadanLab/arcasHLA#34]
This is python why cant I install this via `pip` or `conda`?

**Comment by IoanFilip2** [comment]
Please use this forum to raise issues with our tool. Suggestions are welcome for improving it as well. At this time, we have not packaged the tool for pip/conda installation.

**Comment by xguse** [comment]
This IS an issue with the tool.

**Comment by FriederikeHanssen** [comment]
I agree, and would propose to re-open this issue so it can be addressed, please :)
