### ISSUE TITLE
"arcas reference --version or --update" not working

### ISSUE THREAD

**Issue by fdegenhardt-ikmb** [RabadanLab/arcasHLA#35]
"arcas reference --version" or "--update" is looking for dat/IMGTHLA, which I could not find in the most recent repo.

**Comment by ShahiRB** [comment]
This info can be helpful:

arcasHLA now requires Git Large File Storage to properly download later IMGT/HLA references.

https://github.com/RabadanLab/arcasHLA/issues/4#issue-416305546

**Comment by tpereachamblee** [comment]
Thank you for using our tool. Please see the explanation provided in issue #32.
