### ISSUE TITLE
Typing of DPA1

### ISSUE THREAD

**Issue by tinyheero** [RabadanLab/arcasHLA#38]
Hi there,

Thanks for this tool. Is it possible to use arcasHLA to type DPA1? The documentation contains output for DPB1, but ti doesn't seem to be output for the alpha chain.

Kind regards,

Fong

**Comment by IoanFilip2** [comment]
Dear Fong, thank you for your interest in arcasHLA. The documentation serves and illustrative purpose. When the user does not supply a list of genes to genotype as a parameter, the default option returns genotyping for all the class I, class II and even pseudogenes. In particular, DPA1 is genotyped as well. This is the full list of genes under the default option: 
['A', 'B', 'C', 'DMA', 'DMB', 'DOA', 'DOB', 'DPA1', 'DPB1', 'DQA1', 'DQB1', 'DRA', 'DRB1', 'DRB3', 'DRB5', 'E', 'F', 'G', 'H', 'J', 'K', 'L'].
