### ISSUE TITLE
Requirements for arcasHLA

### ISSUE THREAD

**Issue by s849** [RabadanLab/arcasHLA#39]
Hi,

Thank you for developing arcasHLA. I have a question regarding the requirements for installation of arcasHLA. Will the following dependencies and their versions work (or do they need to be the ones listed in your Github):

kallisto/0.46.2 
bedtools2/2.29.2,
pigz 2.4.1, samtools 1.10 
python/3.8.0, 

Looking forward to hearing from you.

Thank you.

**Comment by IoanFilip2** [comment]
Thanks for your interest in arcasHLA. We are not aware of any incompatibility with the versions that you list; please go ahead and use arcasHLA with your configuration and report here any issue that may arise. The versions that we list in the documentation were the those that we used for testing our tool, and we recommend using those. Eventual updates will be published in the github documentation.
