### ISSUE TITLE
Error in ./arcasHLA reference

### ISSUE THREAD

**Issue by zlskidmore** [RabadanLab/arcasHLA#4]
Hi,

when attempting to switch to IMGT reference 3.24.0 for testing the installation I get the following message:
```
Traceback (most recent call last):
  File "./scripts/reference.py", line 481, in <module>
    build_fasta()
  File "./scripts/reference.py", line 363, in build_fasta
    utrs, exons, final_exon_length) = process_hla_dat()
  File "./scripts/reference.py", line 127, in process_hla_dat
    lines = file.read().splitlines()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 6249748: ordinal not in range(128)
```

I attempted to grab the reference from the git history as well but I get the same error until around version 3.25.0

`./arcasHLA reference --commit 70055402cf42eef5e0d13a1d2ef3b93de0c020f9`

Also if trying to pull the latest version by commit (3.35.0) I see a different error

```
Traceback (most recent call last):
  File "./scripts/reference.py", line 467, in <module>
    build_fasta()
  File "./scripts/reference.py", line 386, in build_fasta
    seq_out, allele_idx, lengths = complete_records(cDNA, other)
  File "./scripts/reference.py", line 308, in complete_records
    offset = i + 1
``` 

which occurs until I get to around 3.33.0 any ideas what happening?

**Comment by roseorenbuch** [comment]
Hi Zachary,

The first error seems to indicate there's some problem with `dat/IMGTHLA/hla.dat`. Do you still get this error when you run the following commands from the arcasHLA directory?
```
rm -rf dat/IMGTHLA
./arcasHLA reference --version 3.24.0 --verbose
```
If so, could you post the output?



The second error is a problem with cloning the IMGTHLA repository. The file `hla.dat` is corrupted when cloned, due to some issue with Git's large file storage. However, `hla.dat` available directly from the [IMGTHLA repository](https://github.com/ANHIG/IMGTHLA) is not corrupted so you could manually replace the one in arcasHLA's database and rebuild the reference.
```
curl https://media.githubusercontent.com/media/ANHIG/IMGTHLA/Latest/hla.dat > dat/IMGTHLA/hla.dat
./arcasHLA reference --rebuild --verbose
```

**Comment by zlskidmore** [comment]
After running:
```
rm -rf dat/IMGTHLA
./arcasHLA reference --version 3.24.0 --verbose
```
I see this:
```

--------------------------------------------------------------------------------
[reference] cloning IMGT/HLA database:

	git clone https://github.com/ANHIG/IMGTHLA.git dat/IMGTHLA/

[reference] checking out IMGT/HLA:

	git -C dat/IMGTHLA/ checkout cfb6db3de7f3a7e76d88467271541ff0cc8fbca1

[reference] IMGT/HLA database version:

cfb6db3de7f3a7e76d88467271541ff0cc8fbca1

[reference] processing IMGT/HLA database
Traceback (most recent call last):
  File "./scripts/reference.py", line 476, in <module>
    build_fasta()
  File "./scripts/reference.py", line 363, in build_fasta
    utrs, exons, final_exon_length) = process_hla_dat()
  File "./scripts/reference.py", line 127, in process_hla_dat
    lines = file.read().splitlines()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 6243347: ordinal not in range(128)
```

I don't know if this will help but i've got a docker image here which I am running on:
https://cloud.docker.com/repository/docker/zlskidmore/arcashla/general

**Comment by zlskidmore** [comment]
if it helps arcasHLA is in `/usr/bin/arcasHLA-master` within that docker image

**Comment by roseorenbuch** [comment]
Ok, I've checked out your docker image. There is no language set (i.e. `echo $LANG` returns nothing). I've added a flag for utf-8 encoding when reading files in the reference and genotype scripts in the dev branch of arcasHLA, so you could replace master with dev in your dockerfile.

You could also add the following to your dockerfile:
```
# Set the locale
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
```
