### ISSUE TITLE
HLA genome types virome data

### ISSUE THREAD

**Issue by warrenlr** [RabadanLab/arcasHLA#41]
Hello,

Thank you for making your tool available.

In your manuscript, you state "We established the HLA genotyping ground truth for the Virome dataset", but I could not find your HLA genotype calls anywhere. 

Similarly, there is no URL to the manhattan virome data / this data is not in public repos.

I would be grateful if you could please share those with us so we can reproduce / compare to your results

Thank you!

**Comment by IoanFilip2** [comment]
Hello! Thank you for your interest in our tool. We were happy to share the genotyping calls in a private correspondence. All the Virome dataset sequence data will be made publicly available with an upcoming publication (still in progress) whose scope extends well beyond HLA genotyping from RNA-seq.
