### ISSUE TITLE
determination of single-end vs paired-end data

### ISSUE THREAD

**Issue by alexvpickering** [RabadanLab/arcasHLA#46]
Note that default behaviour changed with #44 (breaking change).

Old behaviour: set as single-end if one fastq file supplied, paired-end if two supplied.
Change with #44: default is paired-end unless `--single` flag present.
Rationale: can be two fastq.gz files for single-end and e.g. 4 for paired-end (see [kallisto manual](https://pachterlab.github.io/kallisto/manual))

Let me know if you would like to change it back to the old behaviour. It got added to #44 by mistake when I was updating it to reflect my own preference.

**Comment by IoanFilip2** [comment]
Thanks, I think it works as is, with the latest update (#44). May need to
update the README.

Ioan
