### ISSUE TITLE
Can I use arcasHLA for cancer scRNA-seq data?

### ISSUE THREAD

**Issue by levinhein** [RabadanLab/arcasHLA#49]
Can I use arcasHLA for cancer scRNA-seq data?

**Comment by IoanFilip2** [comment]
Thank you for your interest in your tool. At the moment, arcasHLA cannot be used directly for calling HLA alleles in single cells. However, you may use arcasHLA to genotype the tissue of origin by simply processing the single-cell bam file as if it were a single-end bulk sample (by ignoring the cell barcode mate). The pipeline will produce highly accurate genotyping as it normally does for single-end bulk samples. We are in the process of developing a cell-specific approach based on arcasHLA. In the meantime, please let us know if you have follow-up questions.
