### ISSUE TITLE
Problem with module "genotype"

### ISSUE THREAD

**Issue by sebboegel** [RabadanLab/arcasHLA#5]
Dear arcasHLA developer,

I was following the "test" section in the README and did "reference" and "extract". However, when running "genotype" I get warnings and not the expected result. See below:

manager@bl8vbox[arcasHLA] ./arcasHLA reference --version 3.24.0       [ 9:34am]
manager@bl8vbox[arcasHLA] ./arcasHLA extract test/test.bam -o test/output --paired -v     

--------------------------------------------------------------------------------
[log] Date: 2019-03-13
[log] Sample: test
[log] Input file: test/test.bam
[log] Read type: paired-end
--------------------------------------------------------------------------------
[extract] Extracting reads from test/test.bam
[extract] Extracting chromosome 6: 

	samtools view -H -@1 test/test.bam -o /tmp/test.hla.sam

[extract] Extracting chromosome 6: 

	samtools view -@1 -f 2 test/test.bam 6 >> /tmp/test.hla.sam

[extract] Converting SAM to BAM: 

	samtools view -Sb -@1 /tmp/test.hla.sam > /tmp/test.hla.bam

[extract] Sorting bam: 

	samtools sort -n -@1 /tmp/test.hla.bam -o /tmp/test.hla.sorted.bam

[extract] Converting bam to fastq: 

	bedtools bamtofastq -i /tmp/test.hla.sorted.bam -fq test/output/test.extracted.1.fq -fq2 test/output/test.extracted.2.fq

--------------------------------------------------------------------------------

manager@bl8vbox[arcasHLA] ./arcasHLA genotype test/output/test.extracted.1.fq.gz test/output/test.extracted.2.fq.gz -g A,B,C,DPB1,DQB1,DQA1,DRB1 -o test/output -v     

--------------------------------------------------------------------------------
[log] Date: 2019-03-13
[log] Sample: test
[log] Input file(s): test/output/test.extracted.1.fq.gz, test/output/test.extracted.2.fq.gz
[log] Reference: cfb6db3de7f3a7e76d88467271541ff0cc8fbca1

--------------------------------------------------------------------------------
[alignment] Analyzing read length
./scripts/genotype.py:82: UserWarning: genfromtxt: Empty input file: "/tmp/test.reads.txt"
  read_lengths = np.genfromtxt(reads_file)
/home/manager/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/manager/.local/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/manager/.local/lib/python3.6/site-packages/numpy/core/_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/manager/.local/lib/python3.6/site-packages/numpy/core/_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/manager/.local/lib/python3.6/site-packages/numpy/core/_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
[alignment] Pseudoaligning with Kallisto: 

	kallisto pseudo -i dat/ref/hla.idx -t 1 -o /tmp/test/ test/output/test.extracted.1.fq.gz test/output/test.extracted.2.fq.gz

[alignment] processing pseudoalignment
[alignment] Processed 0 reads, 0 pseudoaligned to HLA reference
[alignment] 0 reads mapped to a single HLA gene
[alignment] Observed HLA genes:
		gene          abundance    read count    classes
--------------------------------------------------------------------------------
[genotype] Genotyping parameters:
		population: prior
		max iterations: 1000
		tolerance: 1e-06
		drop iterations: 20
		drop threshold: 0.1
		zygosity threshold: 0.15
--------------------------------------------------------------------------------
[genotype] Genotyping HLA-A
[genotype] No reads aligned to HLA-A
--------------------------------------------------------------------------------
[genotype] Genotyping HLA-B
[genotype] No reads aligned to HLA-B
--------------------------------------------------------------------------------
[genotype] Genotyping HLA-C
[genotype] No reads aligned to HLA-C
--------------------------------------------------------------------------------
[genotype] Genotyping HLA-DPB1
[genotype] No reads aligned to HLA-DPB1
--------------------------------------------------------------------------------
[genotype] Genotyping HLA-DQA1
[genotype] No reads aligned to HLA-DQA1
--------------------------------------------------------------------------------
[genotype] Genotyping HLA-DQB1
[genotype] No reads aligned to HLA-DQB1
--------------------------------------------------------------------------------
[genotype] Genotyping HLA-DRB1
[genotype] No reads aligned to HLA-DRB1
--------------------------------------------------------------------------------

manager@bl8vbox[arcasHLA]                                             [ 9:36am]

**Comment by roseorenbuch** [comment]
This is likely an error during the extract step (no reads aligned to reference, empty read stats). What are the file sizes of `test/output/test.extracted.1.fq.gz` and `test/output/test.extracted.2.fq.gz`?

What is the output when you run the following commands?
```bash
samtools view -H -@1 test/test.bam -o /tmp/test.hla.sam
samtools view -@1 -f 2 test/test.bam 6 >> /tmp/test.hla.sam
samtools view -Sb -@1 /tmp/test.hla.sam > /tmp/test.hla.bam
samtools sort -n -@1 /tmp/test.hla.bam -o /tmp/test.hla.sorted.bam
bedtools bamtofastq -i /tmp/test.hla.sorted.bam -fq test/output/test.extracted.1.fq -fq2 test/output/test.extracted.2.fq
pigz -f -p 1 -S .gz test/output/test.extracted.1.fq
pigz -f -p 1 -S .gz test/output/test.extracted.2.fq
```

**Comment by sebboegel** [comment]
rw-rw-r-- 1 manager manager   40 Mar 13 09:35 test.extracted.1.fq.gz
-rw-rw-r-- 1 manager manager   40 Mar 13 09:35 test.extracted.2.fq.gz

**Comment by sebboegel** [comment]
Thanks a lot for your fast reply. The problem was, that i had samtools 0.19 installed (i had samtools already installed, shortly checked the requirements list and thought I was fine; maybe you add a version number), which outputs "samtools sort - ....... -o) to stdout instead to the file "/tmp/test.hla.sorted.bam". Now, with the new samtools version it works perfectly. Thanks a lot. Great work
