### ISSUE TITLE
Create a new release?

### ISSUE THREAD

**Issue by holtgrewe** [RabadanLab/arcasHLA#50]
Hi, could you create a new release? I'm creating a [bioconda](http://bioconda.github.io/) package right now and it would be nice to have the latest and greatest version up there...

**Comment by holtgrewe** [comment]
FWIW the package for 0.2.0 is here: http://bioconda.github.io/recipes/arcas-hla/README.html

**Comment by IoanFilip2** [comment]
That's great, thank you so much for creating the bioconda package! We are grateful for your contribution. The version you have included in this package is essentially up to date. 

Please note that we are currently developing a new functionality, arcasHLA-quant, to quantify [allele-specific expression](https://www.medrxiv.org/content/10.1101/2020.09.30.20204875v1.full). Provisionally, we have released this functionality [here](https://github.com/roseorenbuch/arcasHLA-quant). After going through peer review, we will officially include these scripts within the arcasHLA repository. At that point, an update should be released for bioconda. Thanks again!

**Comment by eegk** [comment]
Dear author, the dropbox reference link is not longer functional. :'( Thanks.

**Comment by IoanFilip2** [comment]
The dropbox reference is no longer needed: `arcasHLA-quant/dat/ref/` contains all the required files to run.
