### ISSUE TITLE
interpreting *genes.json output

### ISSUE THREAD

**Issue by zuta-osa77** [RabadanLab/arcasHLA#54]
Hi, 

Wondering how to interpret *genes.json output (see below). Thanks!

sm

```
{"A": [9104.0, 3628, 0.18921475974399068], "B": [6499.0, 2754, 0.13618954185635945], "C": [6877.0, 2593, 0.14254001726640184], "DMA": [184.0, 2, 0.005342202898901628], "DMB": [246.0, 4, 0.007088184
725790673], "DOA": [17.0, 6, 0.0005152037872793143], "DPA2": [1.0, 1, 3.113301114046414e-05], "DPB1": [290.0, 119, 0.008517302674554006], "DQB1": [129.0, 70, 0.0036343754745788493], "DRA": [1396.0,
 7, 0.04164367848847119], "DRB1": [536.0, 55, 0.015270644795199345], "DRB5": [216.0, 2, 0.006153841932393766], "E": [9707.0, 1359, 0.20435292065495925], "F": [1112.0, 25, 0.024376938375165955], "HF
E": [63.0, 1, 0.0013731531245993252], "K": [23.0, 5, 0.0004802117427420722], "L": [2298.0, 2, 0.04784808621111001], "T": [2586.0, 1, 0.12857038272586738], "U": [1.0, 1, 0.00011643110798959293], "W"
: [57.0, 8, 0.0013897097633116797], "DRB4": [158.0, 16, 0.004501421413510255], "DPA1": [746.0, 158, 0.021742133953775635], "DOB": [114.0, 13, 0.003164886468271855], "DQA1": [199.0, 68, 0.0059131236
14617295], "DQA2": [1.0, 1, 2.9714189018177362e-05]}
```

**Comment by eegk** [comment]
This is a great question. Please allow me to follow up. All the key statistics are in the log file. 

Dear arcasHLA team, which would be the best way of extracting these into a table?. The script: arcasHLA convert --resolution [resolution] genotypes.tsv , Attempts to do that, but I'm running into errors. 

If there is a way, please provide an example. Otherwise that's fine as well. 


Thank you.
Edgar

**Comment by tpereachamblee** [comment]
Thank you both for your interest in our tool. 

The statistics in the *.genes.json are as follows: (i) The number of reads assigned to each gene, (ii) the number of equivalence classes, and (iii) the relative abundance of each gene. The function that computes these values is `get_count_stats` in [align.py](https://github.com/RabadanLab/arcasHLA/blob/master/scripts/align.py).

Regarding extracting these values into a table, this functionality has been reinstated in the latest release, [v0.4.0](https://github.com/RabadanLab/arcasHLA/releases/tag/v0.4.0).
