### ISSUE TITLE
issue with merge

### ISSUE THREAD

**Issue by zuta-osa77** [RabadanLab/arcasHLA#55]
Hi I'm having some trouble merging *genotype.json and *genes.json results via the merge function, can you please point me in the right direction? 

```
[x@y out]$ ll *genotype*json | wc -l 
1640
[x@y out]$ ll *genes*json | wc -l 
1640
[x@y out]$ mkdir -p merged_results; arcasHLA merge --run test -i . -o merged_results
Traceback (most recent call last):
  File "/hpc/packages/minerva-centos7/arcashla/0.2.0/arcasHLA-0.2.0/scripts/merge.py", line 173, in <module>
    'genes')
  File "/hpc/packages/minerva-centos7/arcashla/0.2.0/arcasHLA-0.2.0/scripts/merge.py", line 92, in process_count
    lines = lines.split('-'*80)[2].split('\n')
IndexError: list index out of range
[x@y out]$ 
```

**Comment by tpereachamblee** [comment]
Hello! Thanks for your interest in our tool. The most recently tagged version of the tool is not presently recommend for use. Please clone the master directly. As of issue #27  and commit 946a9696 we have depreciate the merging of the genes jsons.
