### ISSUE TITLE
Typing of MICA

### ISSUE THREAD

**Issue by prmac** [RabadanLab/arcasHLA#56]
Is this tool able to type MICA? Running 
```
arcasHLA genotype test/output/test.extracted.1.fq.gz test/output/test.extracted.2.fq.gz -g MICA -o test/output -t 8 -v
```
results in 
```
arcasHLA genotype: error: The gene list MICA is invalid.
```

**Comment by IoanFilip2** [comment]
Thanks for your interest in our tool. Unfortunately, we only support HLA class I and class II genotyping at the moment. I think that including MICA alleles in a future release would be a great extension of the project. Thanks for bringing it up to our attention.
