### ISSUE TITLE
Cannot update reference

### ISSUE THREAD

**Issue by zhangz0801** [RabadanLab/arcasHLA#57]
Hi, I can not choose reference version using this command:
`./arcasHLA reference --version 3.24.0`
```
The error information is here:
Traceback (most recent call last):
  File "/cluster/home/zheyang/biosoft/arcasHLA-master/scripts/reference.py", line 548, in <module>
    build_fasta()
  File "/cluster/home/zheyang/biosoft/arcasHLA-master/scripts/reference.py", line 416, in build_fasta
    utrs, exons, final_exon_length) = process_hla_dat()
  File "/cluster/home/zheyang/biosoft/arcasHLA-master/scripts/reference.py", line 134, in process_hla_dat
    with open(hla_dat, 'r', encoding='UTF-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/cluster/home/zheyang/biosoft/arcasHLA-master/scripts/../dat/IMGTHLA/hla.dat'
```

Also, it also can not update reference.
`./arcasHLA reference --updata`
```
usage: arcasHLA reference [options]
arcasHLA reference: error: unrecognized arguments: --updata
```

**Comment by IoanFilip2** [comment]
Hi! Thanks for your interest in our tool. It looks like your folder structure is not correctly set up. The following commands need to be run from your home directory (or wherever you are building it):  
git clone https://github.com/RabadanLab/arcasHLA.git arcasHLA-master
PATH="${PATH}:/home/arcasHLA-master/"
arcasHLA reference --update

Note also the typo in your "--updata" command.
