### ISSUE TITLE
Error in reference --update

### ISSUE THREAD

**Issue by sebboegel** [RabadanLab/arcasHLA#6]
While I am able to do 
./arcasHLA reference --version 3.24.0

running ./arcasHLA reference --update

gives me an error
Traceback (most recent call last):
  File "./scripts/reference.py", line 467, in <module>
    build_fasta()
  File "./scripts/reference.py", line 386, in build_fasta
    seq_out, allele_idx, lengths = complete_records(cDNA, other)
  File "./scripts/reference.py", line 308, in complete_records
    offset = i + 1
UnboundLocalError: local variable 'i' referenced before assignment

**Comment by roseorenbuch** [comment]
There's currently an issue with Github's Large File Storage for the latest version of IMGTHLA (3.35.0) which is corrupting the download of hla.dat when cloning the repository. However, it is still available directly from the [IMGTHLA github](https://github.com/ANHIG/IMGTHLA). You can directly download and rebuild the reference using the commands I've posted [here](https://github.com/RabadanLab/arcasHLA/issues/4#issuecomment-470248597) to obtain the latest version.

**Comment by sebboegel** [comment]
Great. That worked. Thanks a lot.
