### ISSUE TITLE
DRB4 genotype issue

### ISSUE THREAD

**Issue by BenSolomon** [RabadanLab/arcasHLA#60]
Hi team - Thanks for a great tool. I've been using it for a while now and have noticed that in my hands, arcasHLA never assigns genotypes for HLA-DRB4, even in samples that have a known HLA-DRB4 gene by in vitro genotyping. I notice that in my log files that arcasHLA is aligning reads to the DRB4 reference: 

```
[alignment] Observed HLA genes:
		gene          abundance    read count    classes
		HLA-A            20.34%        233078       5353
		HLA-B            20.80%        236351       3928
		HLA-C            16.13%        185309       4063
		HLA-DMA           0.87%          7157          2
		HLA-DMB           0.26%          2138          4
		HLA-DOA           0.05%           360         11
		HLA-DOB           0.06%           507         10
		HLA-DPA1          4.61%         37697        121
		HLA-DPA2          0.00%             7          2
		HLA-DPB1          4.26%         34500        566
		HLA-DPB2          0.01%            56          2
		HLA-DQA1          3.00%         24042        211
		HLA-DQA2          0.00%             1          1
		HLA-DQB1          1.93%         16318        420
		HLA-DRA           6.34%         50618          8
		HLA-DRB1          6.53%         54554        265
		HLA-DRB3          1.00%          8356         15
		HLA-DRB4          0.79%          6631         10
		HLA-DRB5          0.00%            40          4
```

However, in the genotyping section, DRB4 is simply absent

```
[genotype] Genotyping HLA-DRB3
[genotype] 8356 reads aligned to HLA-DRB3 in 15 classes
[genotype] Top 10 alleles by undivided read count:
		allele                  read count	
		DRB3*03:01:01                 8331	
		DRB3*03:01:03                 8246	
		DRB3*02:24                    2420	
		DRB3*02:01                    2416	
		DRB3*02:02:01                 2208	
		DRB3*02:02:20                 2207	
		DRB3*02:02:14                 2206	
		DRB3*02:71                    2206	
		DRB3*01:01:02                  821	
		DRB3*01:01:13                  812	

[genotype] Quantifying allele transcript abundance
[genotype] EM converged after 7 iterations

[genotype] Top alleles by abundance:
		allele                  abundance
		DRB3*03:01:01             100.00%

[genotype] Most likely genotype explaining 8331 reads:
		DRB3*03:01:01
--------------------------------------------------------------------------------
[genotype] Genotyping HLA-DRB5
[genotype] Not enough reads aligned to HLA-DRB5 to genotype.
```

Notice that while DRB5 has fewer reads aligned than DRB4 (and even has fewer reads than necessary to genotype), only DRB5 is explicitly included in the genotyping log, while DRB4 is missing. I am running the `arcasHLA genotype` command without a specific list of HLA loci, so my understanding is that it should default to genotyping all loci. 

Any thoughts as to why HLA-DRB4 is missing?

Thanks!

**Comment by BenSolomon** [comment]
To contribute to my own question, here are some things I've noticed from reviewing the arcasHLA code

- In `alignment.py`, HLA genes are determined based on the allele to which they are pseudoaligned (e.g. HLA-DRB4*01:01 converted to HLA-DRB4 by `get_gene()` in `arcas_utilities.py`). In this case, whether or not arcasHLA would identify HLA-DRB4 in the alignment phase would depend on whether the HLA reference files contain HLA-DRB4 alleles to which suitable reads could be aligned
- In `genotype.py`, HLA genes are determined based on whether they match those included in the `/dat/info/parameters.p` pickle file. DRB4 appears to be missing from this list, which only includes:

```
{'DPB1', 'DPA1', 'H', 'C', 'DMB', 'DOB', 'B', 'A', 'DRA', 'G', 'DQA1', 'F', 'DRB3', 'J', 'DQB1', 'K', 'E', 'DMA', 'DOA', 'DRB5', 'L', 'DRB1'}
```

So my interpretation is that arcasHLA can align to DRB4 because DRB4 alleles are included in an up to date reference, but DRB4 genotyping fails because DRB4 is not included in the list of genes stored in `parameters.p`

Does this explanation seem correct? If so, is there a reason why DRB4 was excluded from the set of genes that arcasHLA performs genotyping on? If this was not intended, I can make a correction and submit a pull request.

**Comment by IoanFilip2** [comment]
Hi Ben! Thank you for your interest in our tool and for the positive feedback on our work. Indeed, by default we only genotype the genes listed in the parameters.p file. At this time, a few genes are missing, like DRB4 and DRB2. Our initial selection may have excluded some genes that were virtually un-detected in the cohorts that we analyzed due to low abundance. But there is no reason to exclude them; in our future release, we plan to default to genotyping all the HLA genes using the same pipeline. It would be great if you made the updates and submitted a pull request. We can do some testing on our end as well. Thanks!
