### ISSUE TITLE
Unable to index 

### ISSUE THREAD

**Issue by srbehera** [RabadanLab/arcasHLA#63]
I am just wondering if I can use cram file instead of bam. I am getting the following error when it runs `samtools`. However, `samtools` does not give any error if I simply run `samtools index A00018.hgv.cram` in command line.
```
--------------------------------------------------------------------------------
[log] Date: 2021-04-02
[log] Sample: A00018
[log] Input file: A00018.hgv.cram
[log] Read type: paired-end
--------------------------------------------------------------------------------
[extract] Extracting reads from A00018.hgv.cram
[extract] indexing bam: 

	samtools index A00018.hgv.cram

[extract] Error: unable to index bam file
```

**Comment by tpereachamblee** [comment]
Thank you for using our tool. Please see issue #68, arcasHLA presently does not support filenames with "." appearing before the file extension. We may update this in a future release.
