### ISSUE TITLE
suggestion: B2M expression levels/SNPs

### ISSUE THREAD

**Issue by EdGreen21** [RabadanLab/arcasHLA#64]
Thanks for this great tool, it's been really useful for our patient data.

One suggestion - because great software always attracts annoying user suggestions - is to expand the tool to assessing the expression levels/SNPs of critical accessory molecules like B2M - though it would be an entirely fair critique to say this is out of scope for this arcasHLA.

Keep up the great work team!

**Comment by tpereachamblee** [comment]
Hi! Thanks for your interest in our tool. We agree that this suggestion is out of scope for arcasHLA, as it was developed to provide fast and accurate in silico inference of HLA genotypes from RNA-seq, specifically.
