### ISSUE TITLE
Version control of IMGT/HLA

### ISSUE THREAD

**Issue by wgmao** [RabadanLab/arcasHLA#65]
I'm currently trying out the latest release version of arcasHLA (v0.2.5). The latest IMGT/HLA version is v3.44.0. I wanted to use a specific version v3.42.0. But  `arcasHLA reference --version 3.24.0` returns `[reference] Error: invalid version. 

Do I need to manually add information about v3.42.0 to `dat/info/parameters.json` in order to fetch v3.42.0? What if I want to do the same thing with arcasHLA (v0.2.0) where the `parameters.json` is not available? Is there a way to manually update the reference database after downloading the files directly from `https://github.com/ANHIG/IMGTHLA`. Thank you in advance.

**Comment by tpereachamblee** [comment]
Hello! Thanks for your interest in our tool. The reference tool has an option to directly pass the commit hash of the IMGT/HLA version you are interested in, i.e. either of the following should build the same reference:

`arcasHLA reference --version 3.24.0` 
`arcasHLA reference --commit c5acf7a4342869351b2382b1cc1d1b5763e7e04e`

The next release will add more reference versions and their commit hashes to the `dat/info/parameters.json` file. Thank you for your constructive feedback.
