### ISSUE TITLE
Fastq as input

### ISSUE THREAD

**Issue by sebboegel** [RabadanLab/arcasHLA#7]
I understand, that input is RNA-seq bam, reads are extracted as .fq and then genotyped. However, is it also possible to use (not extracted) raw fastq files?
I tried using this paired end sample: https://www.ncbi.nlm.nih.gov/sra/ERX002711[accn]

and i get this error:
manager@bl8vbox[arcasHLA] ./arcasHLA genotype test/ERR009111_1.fastq.gz test/ERR009111_2.fastq.gz -g A,B,C,DPB1,DQB1,DQA1,DRB1 test/output/ERR009111
usage: arcasHLA genotype [options] FASTQs or alignment.p file
arcasHLA genotype: error: The format of test/ERR009111_1.fastq.gz is invalid.

**Comment by roseorenbuch** [comment]
Both genotype and partial modules now take files ending in `.fastq.gz` and `.fastq` as input in the latest version.

**Comment by sebboegel** [comment]
Thanks a lot for the fix and thanks a lot for your great work
