### ISSUE TITLE
[extract] Error: unable to index bam file.

### ISSUE THREAD

**Issue by GaelMoBeau** [RabadanLab/arcasHLA#70]
Thank you for this valuable tool

I have been experiencing difficulties running the extract function however. Despite having pre-indexed my bam files with samtools, and thus following the appropriate _my.bam.bai_ strategy, arcasHLA still does not recognize the files as indexed and fails at attempting to index them, returning the following error:
`[extract] Error: unable to index bam file.`

Any suggestions on how to fix this issue?

Thanks in advance

**Comment by tpereachamblee** [comment]
Thank you for using our tool. We cannot replicate the issue you are posting here. Please check if the dependencies are properly installed, and post the exact command as well as the output in that case.

**Comment by tpereachamblee** [comment]
Also please see issue #68, arcasHLA presently does not support filenames with "." appearing before the file extension. This may be the reason you were having this problem. Closing issue.
