### ISSUE TITLE
Unable to reproduce test output

### ISSUE THREAD

**Issue by tpjones15** [RabadanLab/arcasHLA#72]
Similarly to #51, I am unable to reproduce the test case, but with the newest version of arcasHLA. 

I ran arcasHLA by:

```
conda create --name arcas-hla arcas-hla=0.3.0-0 -c bioconda
conda activate arcas-hla

curl -L https://github.com/RabadanLab/arcasHLA/archive/refs/tags/v0.3.0.tar.gz | tar zx
cd arcasHLA-0.3.0/

git lfs install

./arcasHLA reference --version 3.24.0

./arcasHLA extract test/test.bam -o test/output -t 8 -v

./arcasHLA genotype test/output/test.extracted.1.fq.gz test/output/test.extracted.2.fq.gz -g A,B,C,DPB1,DQB1,DQA1,DRB1 -o test/output -t 8 -v
```

I get :

```
{"A": ["A*01:01:01", "A*03:01:01"], 
"B": ["B*39:39:01", "B*07:02:01"],
"C": ["C*01:02:01", "C*08:01:01"], 
"DPB1": ["DPB1*02:01:02", "DPB1*14:01:01"], 
"DQA1": ["DQA1*05:03:01", "DQA1*02:01:01"], 
"DQB1": ["DQB1*06:04:01", "DQB1*02:02:01"], 
"DRB1": ["DRB1*03:02:01", "DRB1*10:01:01"]}
```
compared to the expected:
```
{"A": ["A*01:01:01", "A*03:01:01"], 
"B": ["B*39:01:01", "B*07:02:01"], 
"C": ["C*08:01:01", "C*01:02:01"], 
"DPB1": ["DPB1*14:01:01", "DPB1*02:01:02"], 
"DQA1": ["DQA1*02:01:01", "DQA1*05:03"], 
"DQB1": ["DQB1*02:02:01", "DQB1*06:09:01"], 
"DRB1": ["DRB1*10:01:01", "DRB1*14:02:01"]}
```

I hope I haven't missed something obvious!

**Comment by tpereachamblee** [comment]
Thank you for using our tool. We cannot replicate the issue you are posting here. We tested both the conda environment using the commands you included here and the Docker image specified in the Dockerfile in this repository. In both cases we reproduced the expected results:

```
{"A": ["A*01:01:01", "A*03:01:01"]
 "B": ["B*39:01:01", "B*07:02:01"]
 "C": ["C*08:01:01", "C*01:02:01"]
 "DPB1": ["DPB1*14:01:01", "DPB1*02:01:02"]
 "DQA1": ["DQA1*02:01:01", "DQA1*05:03"]
 "DQB1": ["DQB1*06:09:01", "DQB1*02:02:01"]
 "DRB1": ["DRB1*10:01:01", "DRB1*14:02:01"]}
```

Please try these commands again but specify the verbose `-v` flag when running the `reference` module like so:

`./arcasHLA reference --version 3.24.0 -v`

**Comment by tpjones15** [comment]
Thanks for your response. It's my mistake, apologies. I was using an ancient version of git which wasn't recognising the -C option for checking out the correct IMGTHLA version. As such it was by default using the most up to date IMGT/HLA database. 

Using an up to date git did the job and I reproduce the expected results. 
(That is, after doing)
```
rm -rf dat/IMGTHLA
```
and then re-running 

Apologies for what is probably another naive question but do the input bam files need to be aligned to GRCh38 , or will 37 be fine? 

Thanks again for your help.
