### ISSUE TITLE
Git lfs download of reference files failed (git lfs data quota exceeded)

### ISSUE THREAD

**Issue by fgwinner** [RabadanLab/arcasHLA#74]
Hi,

I've tried cloning the latest version of your repository to be able to quantify HLA expression using
`git clone https://github.com/RabadanLab/arcasHLA.git arcasHLA_v0.4.0`
which failed with the following message:

> Error downloading object: dat/ref/GRCh38.all.noHLA.fasta (d6b75ae): Smudge error: Error downloading dat/ref/GRCh38.all.noHLA.fasta (d6b75ae7a1f7513917047acd642f20e8d9ed510c269a68d50aa1f9e20952a84d): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Can you confirm this problem is on the server end? Would it be possible for you to increase the data quota for this repository?
If not is there a possibility to download the reference files from another source?

Thanks in advance and best regards,
--Frederik

**Comment by tpereachamblee** [comment]
Thank you for using our tool. Our apologies, this was, in fact, a server side issue and which has been resolved by increasing the data quota for this repository.

**Comment by wir963** [comment]
Hey @tpereachamblee , 

I am trying to clone arcasHLA and am getting the same error as @fgwinner reported above. Would it be possible to increase the data quota again? Or point me towards where I could download the reference file not using git-lfs? Command and resulting error included below. 

`git clone git@github.com:RabadanLab/arcasHLA.git`

```
Cloning into 'arcasHLA'...
remote: Enumerating objects: 572, done.
remote: Counting objects: 100% (245/245), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 572 (delta 143), reused 166 (delta 106), pack-reused 327
Receiving objects: 100% (572/572), 11.16 MiB | 3.95 MiB/s, done.
Resolving deltas: 100% (327/327), done.
Downloading dat/ref/GRCh38.all.noHLA.fasta (341 MB)
Error downloading object: dat/ref/GRCh38.all.noHLA.fasta (d6b75ae): Smudge error: Error downloading dat/ref/GRCh38.all.noHLA.fasta (d6b75ae7a1f7513917047acd642f20e8d9ed510c269a68d50aa1f9e20952a84d): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

Best, Welles

**Comment by beichengao** [comment]
Also adding to this as well @tpereachamblee - I'm trying to create a docker installation of Arcas using the Dockerfile provided, and am also running into the same error. 

Is there any way to update the Dockerfile to download the necessary reference files elsewhere to avoid the LFS quotas?

**Comment by mkumar45** [comment]
Hello @tpereachamblee, I am also receiving this error when trying to build the Docker image using the provided Dockerfile. Is it possible to re-open and resolve this issue?

**Comment by vb-william** [comment]
Running into the same error on a Docker image build. Thanks!
