### ISSUE TITLE
Small bug fixes for quant.py

### ISSUE THREAD

**Issue by fgwinner** [RabadanLab/arcasHLA#75]
Dear arcasHLA developers,

first of all: Thanks for supplying this great tool.

I've found a couple of minor bugs/improvement suggestions in the arcasHLA quant code. It would be great if you could fix them as outlined below:

- allow quantification from fastqs not ending in fq.gz but fastq.gz:
change [quant.py line 181](../tree/master/scripts/quant.py#L181) from
```if args.file[0].endswith('.fq.gz'):```
to
```if args.file[0].endswith('.fq.gz') or args.file[0].endswith('.fastq.gz'):```

- fix error on creating tsv output for samples that are homoyzgous for all quantified HLA genes (and make allele ordering in tsv file consistent):
change [quant.py line 258](../tree/master/scripts/quant.py#L258) from:
```df = df[['allele1','allele2', 'allele1_count',  'allele2_count', 'allele2_tpm','allele1_tpm', 'baf']]```
to
```
try:
    df = df[['allele1', 'allele2', 'allele1_count', 'allele2_count', 'allele1_tpm', 'allele2_tpm', 'baf']]
except:
    df = df[['allele1', 'allele1_count', 'allele1_tpm']]
```

Thanks in advance and best regards,
--Frederik

**Comment by tpereachamblee** [comment]
Thank you for using our tool and for the great suggestions. These have been incorporated in the latest commit 4828a47.
