### ISSUE TITLE
arcasHLA reference --update error

### ISSUE THREAD

**Issue by xunzhaoqianlicao** [RabadanLab/arcasHLA#80]
after test with the default bam and my own bam,  I want to update the reference, but back to the error: dat/IMGTHLA/hla.dat empty or corrupted. So, I open the hla.dat file, as the following:
version https://git-lfs.github.com/spec/v1
oid sha256:b14578cdcad97....................
size 215338100

And i wonder how to resolve？
Thanks！

**Comment by mimi3421** [comment]
I have tried to download everything from http://ftp.ebi.ac.uk/pub/databases/ipd/imgt/hla/ to dat/IMGTHLA and run ```arcasHLA reference --rebuild``` to regenerate the reference. But I'm not sure whether it's matter that the version in IMGT's FTP is 3.47.0 at the present time while the newest version listed in info/parameters.json is still 3.46.0.

As to the error, the reference is cloned from https://github.com/ANHIG/IMGTHLA at the time running ```arcasHLA reference --update``` but the file hla.dat has been transfered to LFS by Github as is saying here https://github.com/ANHIG/IMGTHLA#cloning-the-repository . So the file cannot be fetched correctly without additional tools.

**Comment by mwhamgenomics** [comment]
I ran into this as well. Found a workaround by checking out IMGTHLA and fetching from git lfs manually, then rebuilding as mentioned. In Conda:

    $ cd conda_env/share/arcas-hla-0.5.0-0/dat/IMGTHLA
    $ git checkout 8d77b3dd93959663d58ae5b626289d0746edd0e7  # or whatever hash from ../info/parameters.json
    $ git lfs fetch --all
    $ arcasHLA reference --rebuild

**Comment by olekskrav** [comment]
Hi. Thanks to all for raising the issue and for the responses. The method provided above should work.

Generally, to avoid this issue, one needs to install the `git lfs` extension to fetch the reference correctly:
```
apt-get install -y git-lfs
```
After that, the `arcasHLA reference` command should work properly. (Just do not forget to delete the directory `dat/IMGTHLA` before rerunning the command.)

Alternatively, you can use the docker image built with our dockerfile as described [here](/RabadanLab/arcasHLA/tree/master/Docker) which would install all needed tools automatically. 

### Regarding the version numbers
The tool is not limited to the versions listed in `dat/info/parameters.json`. One can switch to any other version of the HLA reference database via the `--commit <commit_hash>` option. For example, for the version 3.47, the corresponding hash value can be obtained via the following command executed from within the `dat/IMGTHLA` folder:
```
git rev-list -n 1 v3.47.0-alpha
```
Also, the hash values for the corresponding versions can be viewed at https://github.com/ANHIG/IMGTHLA/releases

**Comment by hazirliver** [comment]
Hi,

I've encountered an issue with arcasHLA after installation and attempting to update the reference database. Below are the steps I followed and the errors I encountered:

* Installation Steps:
```
conda create --prefix /home/jovyan/HLA/arcas_hla python=3.9
conda activate /home/jovyan/HLA/arcas_hla
conda install arcas-hla -c bioconda -c conda-forge
```

* Issue:
After installation, I attempted to update the reference database using:
```
arcasHLA reference --update
```

This resulted in the following error:
```
[reference] Error: dat/IMGTHLA/hla.dat empty or corrupted.
```

* Troubleshooting Steps:
1. I confirmed that git-lfs is installed on my machine:
```
git-lfs --version
git-lfs/3.4.1 (GitHub; linux amd64; go 1.20.11; git 0898dcbc)
```
2. I followed the troubleshooting steps suggested by mwhamgenomics, including a manual checkout and git lfs fetch, but encountered the same error.
3. I noticed that using an older version of the reference database works fine:
```
arcasHLA reference --version 3.34.0
```
However, updating to version 3.35.0 and higher results in the same error:
```
arcasHLA reference --version 3.35.0
```


I made sure to delete the folder ~/HLA/arcas_hla/share/arcas-hla-0.6.0-0/dat/IMGTHLA between attempts to rebuild the reference.

My conda version is 22.9.0
System: Ubuntu 22.04.1 LTS

Could someone please assist me with resolving this issue?
