### ISSUE TITLE
Issue related to hardcoded relative path

### ISSUE THREAD

**Issue by adeschen** [RabadanLab/arcasHLA#9]
Hi,

We have installed arcasHLA on our server. It works fine. However, the software is using relative paths to find scripts located in the script directory. Same thing for the dat directory. This is an issue as we are using module to run software on the server. The users load arcasHLA module to have access to the path to arcasHLA executable but are not expected to run the code in the software directory. We temporary solved the issue by adding symbolic link to the script and dat directories; however, this is only a temporary patch.

It would be highly appreciated if you could change the usage of hardcoded relative path so that the software could comply to module installation.

On another note, the fact that arcasHLA is calling HLA class II is highly welcomed.

Thanks,
Astrid

**Comment by adeschen** [comment]
This issue has been solved by push #2 
However, arcasHLA is now dependent of coreutils. This should be added to the installation documentation.

Best,
Astrid

**Comment by roseorenbuch** [comment]
Added!
