### ISSUE TITLE
Differences in arguments between Dockerfile and on GitHub README

### ISSUE THREAD

**Issue by ryanpe13002** [RabadanLab/arcasHLA#90]
To whom it may concern,

On the GitHub README file for arcasHLA, the option for determining if the input file is single- or paired-end is "**--single : single-end reads (default: False)**". However, when I download the Dockerfile at **docker://jfx319/arcashla** (obtained pursuant to this Issue raised on this Github repo: https://github.com/RabadanLab/arcasHLA/issues/24) and run "**arcasHLA extract -h**", it lists the available options as: "**--paired paired-end reads, default: False**".

I am wondering which is correct? I will run my script for the time being based on what's in the Dockerfile, but I am confused why there are two different approaches for the same option. Thanks so much!

**Comment by olekskrav** [comment]
Thanks for the question and sorry for the delayed reply.

For the best consistency between the documentation and the code, we recommend using our official Dockerfile located in the [Docker](https://github.com/RabadanLab/arcasHLA/tree/master/Docker) folder.

As for the issue, in version 0.2.5 we changed the default behavior from single-end to paired-end reads, so now one should specify `--single` option to switch from the default paired-end mode to the single-end mode, while previously one had to specify `--paired` option to switch from the default single-end mode to the paired-end mode. It seems that the docker image you mentioned was built using the older version of arcasHLA, hence the discrepancy.
