### ISSUE TITLE
Which genes does arcasHLA support?

### ISSUE THREAD

**Issue by slowkow** [RabadanLab/arcasHLA#93]
[IMGTHLA/alignments release 3.49.0](https://github.com/ANHIG/IMGTHLA/tree/8732e7d4739a911e01f69d2c5bda82ca15ca68a9/alignments) includes:

```
A,B,C,DMA,DMB,DOA,DOB,DPA1,DPB1,DQA1,DQA2,DQB1,DRA,DRB,E,F,G,HFE,MICA,MICB,TAP1,TAP2
```

Can we genotype all of these genes with arcasHLA by using the following command?

```
arcasHLA genotype R1.fq.gz R2.fq.gz -g A,B,C,DMA,DMB,DOA,DOB,DPA1,DPB1,DQA1,DQA2,DQB1,DRA,DRB,E,F,G,HFE,MICA,MICB,TAP1,TAP2
```

Or are we limited only to these genes?

```
A,B,C,DPB1,DQB1,DQA1,DRB1
```

**Comment by olekskrav** [comment]
Hi Kamil. Thank you for your interest in our tool. The choice of genes is limited to the ones listed in the file `dat/info/parameters.json`, which are currently as follows:
```
A,B,C,DMA,DMB,DOA,DOB,DPA1,DPB1,DQA1,DQB1,DRA,DRB1,DRB3,DRB5,E,F,G,H,J,K,L
```

If you do not supply the `-g/--genes` argument, all above genes will be considered by default.

We are planning to add the missing genes in the future release. (Similar issues: #60, #56, #38, #15.)
